services:
  tracker:
    container_name: tracker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./config:/usr/share/tracker/config
      - ./chatters:/usr/share/tracker/chatters
  db:
    image: "postgres:latest"
    env_file: .env
    restart: on-failure
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - tracker_db:/var/lib/postgresql/data/

volumes:
  tracker_db: {}